var lamvyc = function() {


    /*-----------------------------------
     *              Array
     *------------------------------------
     */

    //将ary拆分成size长度的区块，返回拆分后的二维数组
    function chunk(ary, size = 1) {
        if (size >= ary.length) {
            return [ary.slice()]
        }
        let res = []
        let len = ary.length
        for (let i = 0; i < len; i += size) {
            let temp = []
            let end = (i + size) <= len ? i + size : len //end取不到
            for (let j = i; j < end; j++) {
                temp.push(ary[j])
            }
            res.push(temp)
        }
        return res
    }


   

    //--------------String---------------



    return {
        memoize: memoize,
        bindAll: bindAll,
        mixin: mixin,
        curry: curry,
        cloneDeep: cloneDeep,
        flip: flip,
        conforms: conforms,
        negate: negate,
        once: once,
        spread: spread,
        ary: ary,
        unary: unary,
        nthArg: nthArg,
        method: method,
        methodOf: methodOf,
        propertyOf: propertyOf,
        flow: flow,
        pullAt: pullAt,
        uniqueId: uniqueId,
        defaultTo: defaultTo,
        range: range,
        rangeRight: rangeRight,
        words: words,
        truncate: truncate,
        trimStart: trimStart,
        trimEnd: trimEnd,
        trim: trim,
        toUpper: toUpper,
        toLower: toLower,
        startsWith: startsWith,
        split: split,
        replace: replace,
        repeat: repeat,
        parseInt: parseInt,
        padStart: padStart,
        padEnd: padEnd,
        pad: pad,
        lowerFirst: lowerFirst,
        lowerCase: lowerCase,
        upperFirst: upperFirst,
        upperCase: upperCase,
        escapeRegExp: escapeRegExp,
        startCase: startCase,
        snakeCase: snakeCase,
        kebabCase: kebabCase,
        chunk: chunk,
        compact: compact,
        concat: concat,
        uniq: uniq,
        uniqBy: uniqBy,
        uniqWith: uniqWith,
        flattenDeep: flattenDeep,
        flattenDepth: flattenDepth,
        groupBy: groupBy,
        keyBy: keyBy,
        forEach: forEach,
        map: map,
        filter: filter,
        reduce: reduce,
        zip: zip,
        unzip: unzip,
        unzipWith: unzipWith,
        zipObject: zipObject,
        zipObjectDeep: zipObjectDeep,
        zipWith: zipWith,
        keys: keys,
        values: values,
        valuesIn: valuesIn,
        every: every,
        some: some,
        fill: fill,
        sortBy: sortBy,
        isEqual: isEqual,
        reverse: reverse,
        countBy: countBy,
        reduceRight: reduceRight,
        shuffle: shuffle,
        isNaN: isNaN,
        isNull: isNull,
        isNil: isNil,
        isUndefined: isUndefined,
        toArray: toArray,
        sum: sum,
        sumBy: sumBy,
        parseJson: parseJson,
        stringifyJson: stringifyJson,
        forIn: forIn,
        forInRight: forInRight,
        forOwn: forOwn,
        forOwnRight: forOwnRight,
        difference: difference,
        differenceBy: differenceBy,
        differenceWith: differenceWith,
        intersection: intersection,
        intersectionBy: intersectionBy,
        sortedIndex: sortedIndex,
        sortedIndexBy: sortedIndexBy,
        sortedIndexOf: sortedIndexOf,
        sortedLastIndex: sortedLastIndex,
        sortedLastIndexBy: sortedLastIndexBy,
        sortedLastIndexOf: sortedLastIndexOf,
        sortedUniq: sortedUniq,
        sortedUniqBy: sortedUniqBy,
        floor: floor,
        isMatch: isMatch,
        matches: matches,
        property: property,
        get: get,
        toPath: toPath,
        matchesProperty: matchesProperty,
        drop: drop,
        dropRight: dropRight,
        dropWhile: dropWhile,
        dropRightWhile: dropRightWhile,
        findIndex: findIndex,
        findLastIndex: findLastIndex,
        flatten: flatten,
        fromPairs: fromPairs,
        toPairs: toPairs,
        toPairsIn: toPairsIn,
        head: head,
        indexOf: indexOf,
        lastIndexOf: lastIndexOf,
        initial: initial,
        intersectionWith: intersectionWith,
        join: join,
        last: last,
        nth: nth,
        pull: pull,
        pullAll: pullAll,
        pullAllBy: pullAllBy,
        pullAllWith: pullAllWith,
        times: times,
        constant: constant,
        isFunction: isFunction,
        functions: functions,
        functionsIn: functionsIn,
        keysIn: keysIn,
        mapKeys: mapKeys,
        mapValues: mapValues,
        isArguments: isArguments,
        isArray: isArray,
        isBoolean: isBoolean,
        isDate: isDate,
        isEmpty: isEmpty,
        isEqualWith: isEqualWith,
        isArrayLike: isArrayLike,
        isArrayLikeObject: isArrayLikeObject,
        isArrayBuffer: isArrayBuffer,
        isElement: isElement,
        isError: isError,
        isFinite: isFinite,
        isPlainObject: isPlainObject,
        isObjectLike: isObjectLike,
        isObject: isObject,
        isNumber: isNumber,
        isNative: isNative,
        isMap: isMap,
        isLength: isLength,
        toLength: toLength,
        isInteger: isInteger,
        isMatchWith: isMatchWith,
        isRegExp: isRegExp,
        isSafeInteger: isSafeInteger,
        isSet: isSet,
        isString: isString,
        union: union,
        unionBy: unionBy,
        unionWith: unionWith,
        without: without,
        tail: tail,
        take: take,
        takeWhile: takeWhile,
        takeRight: takeRight,
        takeRightWhile: takeRightWhile,
        xor: xor,
        xorBy: xorBy,
        xorWith: xorWith,
        find: find,
        findLast: findLast,
        flatMap: flatMap,
        flatMapDeep: flatMapDeep,
        flatMapDepth: flatMapDepth,
        forEachRight: forEachRight,
        includes: includes,
        invokeMap: invokeMap,
        orderBy: orderBy,
        partition: partition,
        reject: reject,
        sample: sample,
        sampleSize: sampleSize,
        size: size,
        defer: defer,
        delay: delay,
        castArray: castArray,
        conformsTo: conformsTo,
        eq: eq,
        gt: gt,
        gte: gte,
        isTypedArray: isTypedArray,
        isSymbol: isSymbol,
        isWeakMap: isWeakMap,
        isWeakSet: isWeakSet,
        lt: lt,
        lte: lte,
        toNumber: toNumber,
        toInteger: toInteger,
        toFinite: toFinite,
        assign: assign,
        assignIn: assignIn,
        toSafeInteger: toSafeInteger,
        add: add,
        divide: divide,
        ceil: ceil,
        max: max,
        maxBy: maxBy,
        mean: mean,
        meanBy: meanBy,
        min: min,
        minBy: minBy,
        multiply: multiply,
        round: round,
        subtract: subtract,
        clamp: clamp,
        inRange: inRange,
        random: random,
        at: at,
        defaults: defaults,
        defaultsDeep: defaultsDeep,
        findKey: findKey,
        findLastKey: findLastKey,
        has: has,
        hasIn: hasIn,
        invert: invert,
        invertBy: invertBy,
        invoke: invoke,
        merge: merge,
        mergeWith: mergeWith,
        omit: omit,
        omitBy: omitBy,
        pick: pick,
        pickBy: pickBy,
        result: result,
        set: set,
        setWith: setWith,
        transform: transform,
        unset: unset,
        update: update,
        updateWith: updateWith,
        camelCase: camelCase,
        capitalize: capitalize,
        deburr: deburr,
        endsWith: endsWith,
        escape: escape,
        unescape: unescape,
        identity: identity,
    }
}()